[package]
name = "astria-executor"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.4.0"
prost = "0.11.6"
reth-executor = { git = "https://github.com/paradigmxyz/reth" }
tokio = "1.25.0"
tonic = "0.8.3"

[build-dependencies]
tonic-build = "0.8.4"
